Added BLST dependencies, upgrade libsodium & ghcup-0.1.20.0
Buidling x86 docker failed due to missing dependencies:
Error: cabal: Could not resolve dependencies:
[__0] trying: cardano-node-8.7.2 (user goal)
[__1] trying: ouroboros-consensus-0.14.0.0 (dependency of cardano-node)
[__2] trying: cardano-ledger-binary-1.2.1.0 (dependency of
...
Found BLST missing.